spring:
  profiles:
    active:
      - local
    group:
      local:
        - local
      dev:
        - dev
      prod:
        - prod

server:
  servlet:
    context-path: /api

# Actuator 보안 설정
management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: "health"
      base-path: /health-check
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  server:
    port: 8081